# Mudando o diretório para o meu Google Drive para não precisar ficar baixando os datasets novamente.

In [73]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [74]:
!pwd

/content


In [75]:
cd "drive/MyDrive/Doutorado/Disciplinas/[2022.1] [UFF] Processamento de Linguagem Natural - Professora: Aline Marins Paes Carvalho/Trabalhos/Trabalho 2 - POS  e Transfer Learning/"

/content/drive/MyDrive/Doutorado/Disciplinas/[2022.1] [UFF] Processamento de Linguagem Natural - Professora: Aline Marins Paes Carvalho/Trabalhos/Trabalho 2 - POS  e Transfer Learning


In [76]:
!pwd

/content/drive/MyDrive/Doutorado/Disciplinas/[2022.1] [UFF] Processamento de Linguagem Natural - Professora: Aline Marins Paes Carvalho/Trabalhos/Trabalho 2 - POS  e Transfer Learning


# Word Embeddings

Baseado em https://colab.research.google.com/drive/1BuLyMlebp43-3KNn-puezjW5S1CGuSI5?usp=sharing

In [77]:
# !wget http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s50.zip

--2022-06-13 23:20:48--  http://143.107.183.175:22980/download.php?file=embeddings/word2vec/cbow_s50.zip
Connecting to 143.107.183.175:22980... connected.
HTTP request sent, awaiting response... 200 OK
Length: 170360268 (162M) [application/octet-stream]
Saving to: ‘download.php?file=embeddings%2Fword2vec%2Fcbow_s50.zip’

download.php?file=e 100%[===================>] 162.47M  1.60MB/s    in 60s     

2022-06-13 23:21:48 (2.70 MB/s) - ‘download.php?file=embeddings%2Fword2vec%2Fcbow_s50.zip’ saved [170360268/170360268]

Archive:  download.php?file=embeddings%2Fword2vec%2Fcbow_s50.zip
  inflating: cbow_s50.txt            


In [ ]:
# !unzip download.php?file=embeddings%2Fword2vec%2Fcbow_s50.zip

In [78]:
from gensim.models import KeyedVectors
word2vec = KeyedVectors.load_word2vec_format('cbow_s50.txt')
word2vec

In [79]:
word2vec['menino']

array([ 0.047754, -0.190243,  0.290581,  0.035822,  0.2301  , -0.139099,
       -0.232351, -0.119084,  0.327645,  0.160017, -0.5318  ,  0.093309,
       -0.545777, -0.166715,  0.044872, -0.094386, -0.017529, -0.053898,
        0.189092, -0.233779, -0.302459,  0.707696, -0.146762,  0.258651,
        0.25436 , -0.071892,  0.132296, -0.072721,  0.162642,  0.348834,
        0.129191, -0.030967,  0.048024,  0.26683 , -0.076066,  0.352168,
        0.629779, -0.403468, -0.473612,  0.456509,  0.008285,  0.066872,
        0.082632, -0.128989,  0.107645,  0.119981,  0.219388, -0.141599,
       -0.20074 , -0.30657 ], dtype=float32)

In [80]:
word2vec.most_similar('homem')

[('monstro', 0.9085395336151123),
 ('bebé', 0.9072304368019104),
 ('indivíduo', 0.9050755500793457),
 ('rapaz', 0.9036116003990173),
 ('mendigo', 0.9007540345191956),
 ('rapazola', 0.8992964625358582),
 ('novelo', 0.8938027620315552),
 ('pássaro', 0.889799952507019),
 ('cão', 0.8882535099983215),
 ('cãozinho', 0.8869854807853699)]

In [81]:
word2vec.similarity('menino', 'cachorro')

0.8441181

In [82]:
word2vec.most_similar(positive=['amar', 'odiando'], negative=['odiar'])

[('amando', 0.7472066879272461),
 ('desperto', 0.7231094837188721),
 ('quieto', 0.6835169196128845),
 ('tranqüilo', 0.68125319480896),
 ('surdo', 0.6798273921012878),
 ('louco', 0.6784767508506775),
 ('quieta', 0.6757060289382935),
 ('sã³brio', 0.6748781800270081),
 ('rouco', 0.6719405651092529),
 ('sossegado', 0.6716687679290771)]

# Pre-Train Word Embedding in PyTorch

Baseado em https://androidkt.com/pre-train-word-embedding-in-pytorch/

In [83]:
# !wget http://nlp.stanford.edu/data/wordvecs/glove.6B.zip

--2022-06-13 23:22:28--  http://nlp.stanford.edu/data/wordvecs/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/wordvecs/glove.6B.zip [following]
--2022-06-13 23:22:28--  https://nlp.stanford.edu/data/wordvecs/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/wordvecs/glove.6B.zip [following]
--2022-06-13 23:22:29--  http://downloads.cs.stanford.edu/nlp/data/wordvecs/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182753 (822M) [applic

In [ ]:
# !unzip glove.6B.zip

In [84]:
import pandas as pd
glove = pd.read_csv('glove.6B.100d.txt', sep=" ", quoting=3, header=None, index_col=0)
glove_embedding = {key: val.values for key, val in glove.T.items()}

In [85]:
import tensorflow as tf
import numpy as np

def create_embedding_matrix(word_index,embedding_dict,dimension):
  embedding_matrix=np.zeros((len(word_index)+1,dimension))
 
  for word,index in word_index.items():
    if word in embedding_dict:
      embedding_matrix[index]=embedding_dict[word]
  return embedding_matrix
 
text=["The cat sat on mat","we can play with model"]
 
tokenizer=tf.keras.preprocessing.text.Tokenizer(split=" ")
tokenizer.fit_on_texts(text)
 
text_token=tokenizer.texts_to_sequences(text)
 
embedding_matrix=create_embedding_matrix(
    tokenizer.word_index,
    embedding_dict=glove_embedding,
    dimension=100)

In [86]:
text_token

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [87]:
tokenizer.word_index

{'can': 7,
 'cat': 2,
 'mat': 5,
 'model': 10,
 'on': 4,
 'play': 8,
 'sat': 3,
 'the': 1,
 'we': 6,
 'with': 9}

In [88]:
import torch
import torch.nn as nn

vocab_size=embedding_matrix.shape[0]
vector_size=embedding_matrix.shape[1]
 
embedding=nn.Embedding(num_embeddings=vocab_size,embedding_dim=vector_size)

In [89]:
embedding.weight=nn.Parameter(torch.tensor(embedding_matrix,dtype=torch.float32))

In [90]:
embedding(torch.LongTensor([1]))

tensor([[-0.0382, -0.2449,  0.7281, -0.3996,  0.0832,  0.0440, -0.3914,  0.3344,
         -0.5755,  0.0875,  0.2879, -0.0673,  0.3091, -0.2638, -0.1323, -0.2076,
          0.3340, -0.3385, -0.3174, -0.4834,  0.1464, -0.3730,  0.3458,  0.0520,
          0.4495, -0.4697,  0.0263, -0.5415, -0.1552, -0.1411, -0.0397,  0.2828,
          0.1439,  0.2346, -0.3102,  0.0862,  0.2040,  0.5262,  0.1716, -0.0824,
         -0.7179, -0.4153,  0.2033, -0.1276,  0.4137,  0.5519,  0.5791, -0.3348,
         -0.3656, -0.5486, -0.0629,  0.2658,  0.3020,  0.9977, -0.8048, -3.0243,
          0.0125, -0.3694,  2.2167,  0.7220, -0.2498,  0.9214,  0.0345,  0.4674,
          1.1079, -0.1936, -0.0746,  0.2335, -0.0521, -0.2204,  0.0572, -0.1581,
         -0.3080, -0.4162,  0.3797,  0.1501, -0.5321, -0.2055, -1.2526,  0.0716,
          0.7056,  0.4974, -0.4206,  0.2615, -1.5380, -0.3022, -0.0734, -0.2831,
          0.3710, -0.2522,  0.0162, -0.0171, -0.3898,  0.8742, -0.7257, -0.5106,
         -0.5203, -0.1459,  

In [91]:
embedding.weight.requires_grad=False

In [92]:
embedding_vec=embedding(torch.LongTensor(text_token))
print(embedding)
print(embedding_vec.shape)

Embedding(11, 100)
torch.Size([2, 5, 100])


In [93]:
embedding_dim=vector_size
lstm=nn.LSTM(embedding_dim,128,bidirectional=True,batch_first=True)(embedding_vec)
lstm

(tensor([[[ 0.0294, -0.0968, -0.0618,  ...,  0.0936,  0.0588,  0.0329],
          [ 0.0009, -0.0113,  0.0264,  ...,  0.0776,  0.0696, -0.0025],
          [-0.0274, -0.0991, -0.0305,  ...,  0.0622,  0.0385,  0.1160],
          [-0.0125, -0.0931,  0.0946,  ...,  0.1278,  0.0946, -0.0558],
          [ 0.0382, -0.1083,  0.0845,  ...,  0.0812,  0.0982, -0.0679]],
 
         [[ 0.0227, -0.1032,  0.0542,  ...,  0.0688,  0.0428, -0.0040],
          [ 0.0758, -0.1596,  0.0624,  ...,  0.0737,  0.0669, -0.0095],
          [ 0.1236, -0.1146,  0.0667,  ...,  0.0565,  0.0367, -0.0545],
          [ 0.0411, -0.0807,  0.0586,  ...,  0.0327,  0.0499, -0.0277],
          [ 0.0435, -0.0697,  0.0235,  ...,  0.0005,  0.0724, -0.0294]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[ 0.0382, -0.1083,  0.0845,  0.0403,  0.0590,  0.0583, -0.0088,
            -0.0112,  0.1354, -0.0874, -0.0189,  0.0089, -0.0761,  0.0647,
             0.0745,  0.0204,  0.0393,  0.0553,  0.0390,  0.1281,  0.0952,
           

# Nova tentativa de treinar o GRU com embeddings pré-treinados.

In [258]:
# word2vec['menino']

In [259]:
# word2vec['pad']

In [260]:
# word2vec['oov']

In [261]:
# word2vec.vocab

In [262]:
# word2vec.vectors

In [263]:
'''
{'can': 7,
 'cat': 2,
 'mat': 5,
 'model': 10,
 'on': 4,
 'play': 8,
 'sat': 3,
 'the': 1,
 'we': 6,
 'with': 9}
 '''

"\n{'can': 7,\n 'cat': 2,\n 'mat': 5,\n 'model': 10,\n 'on': 4,\n 'play': 8,\n 'sat': 3,\n 'the': 1,\n 'we': 6,\n 'with': 9}\n "

In [264]:
# word2index = {token: token_index for token_index, token in enumerate(word2vec.index2word)}
# word2index['menino']

In [265]:
# word2index

In [266]:
# glove_embedding

In [267]:
'''
{'the': array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
        -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
         0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
        -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,
         0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,
        -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,
         0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,
         0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,
        -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,
        -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,
        -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,
        -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,
        -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,
        -1.2526  ,  0.071624,  0.70565 ,  0.49744 , -0.42063 ,  0.26148 ,
        -1.538   , -0.30223 , -0.073438, -0.28312 ,  0.37104 , -0.25217 ,
         0.016215, -0.017099, -0.38984 ,  0.87424 , -0.72569 , -0.51058 ,
        -0.52028 , -0.1459  ,  0.8278  ,  0.27062 ]),
 ',': array([-0.10767  ,  0.11053  ,  0.59812  , -0.54361  ,  0.67396  ,
 [...]
'''

"\n{'the': array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,\n        -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,\n         0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,\n        -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,\n         0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,\n        -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,\n         0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,\n         0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,\n        -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,\n        -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,\n        -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,\n        -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,\n        -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,\n        -1.2526

In [268]:
# word2vec_embedding = {}

# for index, token in enumerate(word2vec.vocab):
#     if index < 3:
#         print(f'token: {token}')
#         print(f'embeddings: {word2vec[token]}')

#         {'the': array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
#         -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
#          0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
#         -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,
#          0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,
#         -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,
#          0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,
#          0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,
#         -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,
#         -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,
#         -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,
#         -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,
#         -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,
#         -1.2526  ,  0.071624,  0.70565 ,  0.49744 , -0.42063 ,  0.26148 ,
#         -1.538   , -0.30223 , -0.073438, -0.28312 ,  0.37104 , -0.25217 ,
#          0.016215, -0.017099, -0.38984 ,  0.87424 , -0.72569 , -0.51058 ,
#         -0.52028 , -0.1459  ,  0.8278  ,  0.27062 ]),
#  ',': array([-0.10767  ,  0.11053  ,  0.59812  , -0.54361  ,  0.67396  ,
#  [...]
#  '''

In [269]:
# def create_embedding_matrix_word2vec(word_index,embedding_dict,dimension):
#   embedding_matrix=np.zeros((len(word_index)+1,dimension))
 
#   for word,index in word_index.items():
#     if word in embedding_dict:
#       embedding_matrix[index]=embedding_dict[word]
#   return embedding_matrix
 
# embedding_matrix_word2vec=create_embedding_matrix(
#     word2index,
#     embedding_dict=glove_embedding,
#     dimension=100)

In [270]:
# !wget http://143.107.183.175:22980/download.php?file=embeddings/glove/glove_s100.zip

In [271]:
# !unzip download.php?file=embeddings%2Fglove%2Fglove_s100.zip

In [272]:
glove_pt = pd.read_csv(
    'glove_s100.txt', 
    sep=" ", 
    quoting=3, 
    header=None, 
    index_col=0,
    skiprows=1)

In [273]:
glove_pt.head()

1         2         3         4         5         6         7    \
0                                                                          
,  -0.392279 -0.383096 -0.163537 -1.615735 -0.500976 -0.007344  0.465154   
de -0.059871 -0.266130 -1.288952 -2.352894  0.414237  0.621193  1.073003   
.  -0.316228  0.152535 -0.348308 -1.317098 -0.343182  0.486299 -0.361778   
a  -1.186349 -0.385310 -0.378241 -2.474666  0.707291  0.086132  0.244584   
o  -0.540110 -0.063359  0.194538 -2.323175 -0.100174  1.276602  0.238280   

         8         9         10   ...       91        92        93        94   \
0                                 ...                                           
,  -0.527951 -0.646091 -0.321491  ... -0.497059  1.318589 -0.233006 -0.156836   
de -0.548189 -0.643191  0.966722  ... -0.388322  1.054918 -0.412016  0.565986   
.  -0.758097 -0.200598  0.647857  ... -0.692086  0.909492 -0.121445 -0.189453   
a  -0.624107 -0.237829  0.392953  ... -0.316421  1.011388  0.202223 -0.575371   
o  -0.623534 -0.347138 -0.129575  ...  0.323425  1.159988 -0.642872 -1.545277   

         95        96        97        98        99        100  
0                                                               
,   0.445024  0.582988  0.177718  0.774904  2.415028 -0.148173  
de  0.697279 -0.073342  0.275684  0.049941  2.603193  0.559911  
.   0.740305  0.316062  0.507474  0.699510  2.571814  0.632679  
a   0.026287 -0.275881  0.052405  0.313878  3.199491  0.827020  
o   0.151334 -0.785550  0.704339  1.013909  2.478992 -0.193909  

[5 rows x 100 columns]

In [274]:
glove_pt.tail()

1         2         3         4         5         6         7    \
0                                                                              
~$0.0b  0.023192  0.042274 -0.136690  0.096456 -0.024662  0.064788 -0.119517   
~.      0.109924 -0.039958 -0.114303  0.271989  0.022783  0.019153 -0.197778   
~>      0.091712 -0.137760 -0.148611  0.280811 -0.040886 -0.156137 -0.345717   
~~     -0.029480 -0.069960 -0.124492  0.287964 -0.103688 -0.109228 -0.165033   
<unk>   0.077257  0.064637 -0.029866  0.150767 -0.004830 -0.024283 -0.078053   

             8         9         10   ...       91        92        93   \
0                                     ...                                 
~$0.0b -0.017335  0.140895  0.030265  ...  0.283668 -0.092165  0.006212   
~.     -0.027550  0.036257 -0.106391  ...  0.012212 -0.060298  0.015915   
~>      0.131649 -0.047881 -0.126024  ...  0.091572  0.002053  0.144309   
~~      0.106509 -0.014567 -0.223258  ...  0.158334 -0.154956 -0.081261   
<unk>   0.034162  0.049797 -0.111888  ...  0.059529 -0.140611  0.036282   

             94        95        96        97        98        99        100  
0                                                                             
~$0.0b  0.041488 -0.003957 -0.003753  0.025884 -0.059045  0.213298 -0.000441  
~.     -0.016765 -0.109300  0.064726 -0.048884  0.034652 -0.218065  0.065903  
~>     -0.234035 -0.003793  0.038706  0.107760  0.125965 -0.256933  0.107929  
~~      0.057896 -0.140982  0.074473 -0.101146 -0.107334  0.052051  0.020874  
<unk>   0.008047 -0.034854  0.027526 -0.075541 -0.054225 -0.150991 -0.027147  

[5 rows x 100 columns]

In [275]:
glove_embedding_pt = {key: val.values for key, val in glove_pt.T.items()}

In [276]:
# glove_embedding_pt

In [277]:
# text_pt = ["The cat sat on mat","we can play with model"]
text_pt = ["PT em o governo", "BRASÍLIA Pesquisa Datafolha publicada hoje revela um dado supreendente: recusando uma postura radical, a esmagadora maioria (77%) dos eleitores quer o PT participando do Governo Fernando Henrique Cardoso.", "Tem sentido -- aliás, muitíssimo sentido."]

tokens = text_pt[1].split()
print(f'tokens (large sentence): {tokens}')
print(f'len(tokens) (large sentence): {len(tokens)}')
print()

max_length = 0
for sentence in text_pt:
    tokens = sentence.split()
    len_tokens = len(tokens)
    if len_tokens > max_length:
        max_length = len_tokens

for index, sentence in enumerate(text_pt):
    tokens = sentence.split()
    len_tokens = len(tokens)
    if len_tokens < max_length:
        difference = max_length - len_tokens
        for i in range(0, difference):
            tokens.append( '<unk>' )
    text_pt[index] = ' '.join(tokens)

for sentence in text_pt:
    tokens = sentence.split()
    print(f'tokens: {tokens}')
    print(f'len(tokens): {len(tokens)}')

print()
print(len(text_pt))

tokens (large sentence): ['BRASÍLIA', 'Pesquisa', 'Datafolha', 'publicada', 'hoje', 'revela', 'um', 'dado', 'supreendente:', 'recusando', 'uma', 'postura', 'radical,', 'a', 'esmagadora', 'maioria', '(77%)', 'dos', 'eleitores', 'quer', 'o', 'PT', 'participando', 'do', 'Governo', 'Fernando', 'Henrique', 'Cardoso.']
len(tokens) (large sentence): 28

tokens: ['PT', 'em', 'o', 'governo', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>', '<unk>']
len(tokens): 28
tokens: ['BRASÍLIA', 'Pesquisa', 'Datafolha', 'publicada', 'hoje', 'revela', 'um', 'dado', 'supreendente:', 'recusando', 'uma', 'postura', 'radical,', 'a', 'esmagadora', 'maioria', '(77%)', 'dos', 'eleitores', 'quer', 'o', 'PT', 'participando', 'do', 'Governo', 'Fernando', 'Henrique', 'Cardoso.']
len(tokens): 28
tokens: ['Tem', 'sentido', '--', 'aliás,', 'muitíssimo', 'sentido.',

In [278]:
def create_embedding_matrix_pt( word_index, embedding_dict, dimension ):
  embedding_matrix = np.zeros( (len(word_index)+1, dimension) )
 
  for word,index in word_index.items():
    if word in embedding_dict:
      embedding_matrix[index]=embedding_dict[word]
  return embedding_matrix
 
tokenizer_pt = tf.keras.preprocessing.text.Tokenizer(split=" ")
tokenizer_pt.fit_on_texts(text_pt)
 
# Trying to solve a bug.
total_sentences = len(text_pt)
last_sentence = text_pt[total_sentences - 1]
last_sentence_tokens = last_sentence.split()
last_sentence_tokens.append( '<unk>' )
text_pt[total_sentences - 1] = ' '.join( last_sentence_tokens )

text_token_pt = tokenizer_pt.texts_to_sequences(text_pt)
 
embedding_matrix_pt = create_embedding_matrix_pt(
    tokenizer_pt.word_index,
    embedding_dict = glove_embedding_pt,
    dimension = 100)

In [279]:
for item in text_token_pt:
    print(len(item))
    print(item)
    print('-------------------------')
    print()

28
[2, 6, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
-------------------------

28
[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 3, 2, 27, 28, 4, 29, 30, 31]
-------------------------

28
[32, 5, 33, 34, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
-------------------------



In [280]:
embedding_matrix_pt

array([[ 0.      ,  0.      ,  0.      , ...,  0.      ,  0.      ,
         0.      ],
       [ 0.156559,  0.111655, -0.015184, ..., -0.009003, -0.178693,
        -0.02881 ],
       [-0.360137,  0.413591,  0.595686, ..., -0.271249,  0.947247,
        -0.11366 ],
       ...,
       [-0.447209,  0.020918, -0.909347, ..., -0.163448,  2.087506,
        -0.756201],
       [ 0.409635, -0.1308  , -0.343453, ...,  0.576715,  1.726277,
        -0.463   ],
       [-0.374381, -0.641518, -0.083434, ...,  0.759932,  0.753288,
        -0.396907]])

In [281]:
vocab_size_pt = embedding_matrix_pt.shape[0]
vector_size_pt = embedding_matrix_pt.shape[1]
 
embedding_pt = nn.Embedding(
    num_embeddings = vocab_size_pt,
    embedding_dim = vector_size_pt)

In [282]:
embedding_pt

Embedding(35, 100)

In [283]:
embedding_pt.weight = nn.Parameter(
    torch.tensor( 
        embedding_matrix_pt,
        dtype = torch.float32))

In [284]:
embedding_pt

Embedding(35, 100)

In [285]:
embedding_pt( torch.LongTensor([1]) )

tensor([[ 0.1566,  0.1117, -0.0152,  0.2379, -0.0216, -0.0107,  0.1072,  0.0079,
          0.0494, -0.0778, -0.0899,  0.0529, -0.0396,  0.2029, -0.0374,  0.1199,
          0.0809,  0.1342, -0.0090, -0.0834, -0.0824, -0.0700,  0.1080,  0.2166,
          0.1193, -0.0090, -0.1851, -0.1200,  0.0541, -0.1695, -0.0515,  0.0963,
         -0.0076,  0.0464, -0.0442,  0.0612, -0.0656,  0.0922,  0.2037, -0.0509,
          0.0409, -0.0548,  0.1614, -0.2111,  0.0966,  0.0693, -0.0541, -0.0616,
         -0.0084, -0.0246, -0.1267,  0.0437, -0.0291,  0.0008, -0.0207,  0.0924,
          0.0360,  0.0383,  0.1084,  0.0118, -0.0112, -0.0261,  0.1788, -0.0073,
          0.0591, -0.0003, -0.0276,  0.0295, -0.1592,  0.1003,  0.0111,  0.0169,
         -0.0067,  0.1499, -0.2063, -0.1196,  0.0076, -0.0756,  0.1790,  0.1040,
          0.0168,  0.2922,  0.1378,  0.1308, -0.0529,  0.1065,  0.1111,  0.1954,
          0.0441,  0.0470, -0.0312, -0.2474, -0.0717,  0.0511,  0.0974,  0.0909,
          0.0424, -0.0090, -

Make it untrainable by freezing its gradient.

In [286]:
embedding_pt.weight.requires_grad = False

In [287]:
for item in text_token_pt:
    print(len(item))
    print(item)
    print('-------------------------')
    print()

28
[2, 6, 3, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
-------------------------

28
[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 3, 2, 27, 28, 4, 29, 30, 31]
-------------------------

28
[32, 5, 33, 34, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
-------------------------



In [288]:
temp = [32, 5, 33, 34, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
len(temp)

27

In [289]:
torch.LongTensor(text_token_pt)

tensor([[ 2,  6,  3,  4,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
         25, 26,  3,  2, 27, 28,  4, 29, 30, 31],
        [32,  5, 33, 34,  5,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [290]:
embedding_vec_pt = embedding_pt(
    torch.LongTensor(text_token_pt))
print(embedding_pt)
print(embedding_vec_pt.shape)

Embedding(35, 100)
torch.Size([3, 28, 100])
